### ISSUE TITLE
Error running UCS Asbuilt

### ISSUE THREAD

**Issue by sanjeshkishore** [AsBuiltReport/AsBuiltReport.Cisco.UcsManager#7]
I am getting an error when running UCS As Built. No issues with VMware As Built. Error below:

New-AsBuiltReport : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:1 char:1
+ New-AsBuiltReport -Report Cisco.UCSManager -Target 172.16.16.70
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by tpcarman** [comment]
Hi @sanjeshkishore,

Could you please provide me with some more information. Does the script execute and then fail with an error or are you unable to execute at all?

Do you have the Cisco UCS PowerTool cmdlets and the AsBuiltReport.Cisco.UcsManager module installed?

**Comment by sanjeshkishore** [comment]
Hi Tim,

Thanks for getting back quickly. Yes script starts to run and I can see it starts to collect info from the UCS but fails when it tries to dump it into the file. I tried to update with older module, which had different command syntax (-Type UCS vs -Report Cisco.UCSManager). Now its not running at all. I may need to clean it out and install again. I had UCS PowerTool installed.

**Comment by sanjeshkishore** [comment]
I have pasted last outputs below:
-----------------------------------------

VERBOSE: [ 15:28:54:840 ] [ Document ] - Processing section 'Chassis/FEX Discovery Policy' started.
VERBOSE: [ 15:28:54:871 ] [ Document ] - Processing table 'Chassis/FEX Discovery Policy'.
VERBOSE: [ 15:28:54:886 ] [ Document ] - Processing section 'Chassis/FEX Discovery Policy' completed.
VERBOSE: [ 15:28:54:965 ] [ Document ] - Processing section 'Rack Server Discovery Policy' started.
VERBOSE: [ 15:28:54:981 ] [ Document ] - Processing table 'Rack Server Discovery Policy'.
VERBOSE: [ 15:28:54:996 ] [ Document ] - Processing section 'Rack Server Discovery Policy' completed.
VERBOSE: [ 15:28:55:059 ] [ Document ] - Processing section 'Power Policy' started.
VERBOSE: [ 15:28:55:074 ] [ Document ] - Processing table 'Power Policy'.
VERBOSE: [ 15:28:55:089 ] [ Document ] - Processing section 'Power Policy' completed.
VERBOSE: [ 15:28:55:168 ] [ Document ] - Processing section 'Global Power Allocation Policy' started.
VERBOSE: [ 15:28:55:183 ] [ Document ] - Processing table 'Global Power Allocation Policy'.
VERBOSE: [ 15:28:55:199 ] [ Document ] - Processing section 'Global Power Allocation Policy' completed.
VERBOSE: [ 15:28:55:214 ] [ Document ] - Processing section 'Global Policies' completed.
VERBOSE: [ 15:28:55:231 ] [ Document ] - Processing section 'Equipment' completed.
VERBOSE: [ 15:28:55:231 ] [ Document ] - Processing section 'Servers' started.
VERBOSE: [ 15:28:55:371 ] [ Document ] - Processing section 'Service Profiles' started.
VERBOSE: [ 15:28:55:387 ] [ Document ] - Processing section 'rack-unit-1' started.
VERBOSE: [ 15:28:55:465 ] [ Document ] - Processing table 'rack-unit-1 Service Profile'.
VERBOSE: [ 15:28:55:512 ] [ Document ] - Processing section 'rack-unit-1' completed.
VERBOSE: [ 15:28:55:512 ] [ Document ] - Processing section 'rack-unit-2' started.
VERBOSE: [ 15:28:55:527 ] [ Document ] - Processing table 'rack-unit-2 Service Profile'.
VERBOSE: [ 15:28:55:527 ] [ Document ] - Processing section 'rack-unit-2' completed.
VERBOSE: [ 15:28:55:542 ] [ Document ] - Processing section 'rack-unit-3' started.
VERBOSE: [ 15:28:55:542 ] [ Document ] - Processing table 'rack-unit-3 Service Profile'.
VERBOSE: [ 15:28:55:542 ] [ Document ] - Processing section 'rack-unit-3' completed.
VERBOSE: [ 15:28:55:558 ] [ Document ] - Processing section 'Service Profiles' completed.
VERBOSE: [ 15:28:55:605 ] [ Document ] - Processing section 'Service Profile Templates' started.
New-AsBuiltReport : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:1 char:1
+ New-AsBuiltReport -Report Cisco.UCSManager -Target 172.16.16.70 -User ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by tpcarman** [comment]
Yes, so this relates to issue #6. Follow the instructions within to resolve the issue.

**Comment by sanjeshkishore** [comment]
Thanks Tim, Will give it shot and let you know.

**Comment by sanjeshkishore** [comment]
All good. Thanks for your help.
